apiVersion: v1
kind: Service
metadata:
  name: statistics
  annotations:
    #alb.ingress.kubernetes.io/healthcheck-path: "/contents/aws"
    #alb.ingress.kubernetes.io/healthcheck-path: "/" # default
spec:
  selector:
    app: statistics
  type: ClusterIP
  ports:
    - port: 80 # 서비스가 생성할 포트  
      targetPort: 8080 # 서비스가 접근할 pod의 포트
      protocol: TCP